# this file defines the tables shown in the elegant summary
# [<display name>, <elegant name>]

machine_parameter = [
    ["Energy $E$", "energy"],
    ["Periodicity $N$", "periodicity"],
    ["Cell length / m", "cell_length"],
    ["Cell Angle / rad", "cell_angle"],
    ["Cell Angle / degree	", "cell_angle_degree"],
    ["Circumference", "circumference"],
]

global_parameter = [
    ["Natural Emittance / rad m", "ex0"],
    ["Energy loss per turn $U_0$ / Mev", "U0"],
    ["Momentum compaction factor $\\alpha_c$", "alphac"],
    ["$\\alpha_{c2}$", "alphac2"],
    ["$J_{\\delta}$", "Jdelta"],
    ["$\\tau_{\\delta}$", "taudelta"],
]

twiss_x = [
    ["$Q_x$", "nux"],
    ["$dnux/dp$", "dnux/dp"],
    ["$dnux/dp 2$", "dnux/dp2"],
    ["$dnux/dp 3$", "dnux/dp3"],
    ["max($\\beta_x$)", "betaxMax"],
    ["min($\\beta_x$)", "betaxMin"],
    ["mean($\\beta_x$)", "betaxAve"],
    ["max($\\eta_x$)", "etaxMax"],
    ["$J_x$", "Jx"],
    ["$\\tau_x$", "taux"],
]

twiss_y = [
    ["$Q_y$", "nuy"],
    ["$dnuy/dp$", "dnuy/dp"],
    ["$dnuy/dp 2$", "dnuy/dp2"],
    ["$dnuy/dp 3$", "dnuy/dp3"],
    ["max($\\beta_y$)", "betayMax"],
    ["min($\\beta_y$)", "betayMin"],
    ["mean($\\beta_y$)", "betayAve"],
    ["max($\\eta_y$)", "etayMax"],
    ["$J_y$", "Jy"],
    ["$\\tau_y$", "tauy"],
]
